# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14-stretch
    steps:
      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build website 
      run: |
        cd $GITHUB_WORKSPACE
        yarn
        yarn prod
      
    - name: Upload to pinata 
      uses: aquiladev/ipfs-action@master
      with:
        path: ./build
