# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [ ubuntu-18.04 ]

    steps:
      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.4.4
    
    - name: Install global NPM packages
      run: npm install --global yarn ipfs-deploy
      
    - name: Build website 
      run: |
        cd $GITHUB_WORKSPACE
        yarn
        yarn prod
      
    - name: Upload to pinata 
      run: mkdir -p /tmp/hash/ && ipfs-deploy -s apocryph.network -p pinata build/ -C -O > /tmp/hash/hash.txt
      env:
        IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.pinataApiKey }}
        IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.pinataApiSecret }}
  
    - name: Make artifact
      uses: actions/upload-artifact@v1
      with:
        name: hash.txt
        path: /tmp/hash/
