# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14-stretch
    steps:
      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build website 
      run: |
        cd $GITHUB_WORKSPACE
        yarn
        yarn prod
      
    - name: Upload website
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container: node:16-stretch
    steps:
      
    - name: Download website
      uses: actions/download-artifact@v3
      with:
        name: website
        path: deployment/website/
    
    - name: Upload to ipfs
      env:
        IPFS_URL: https://apocryph-ipfs.kubocloud.io/api/v0
        IPFS_FOLDER: deployment
        CF_ID: ${{ secrets.CF_ID }}
        CF_SECRET: ${{ secrets.CF_SECRET }}
      run: |
        cd $GITHUB_WORKSPACE
        npm i kubo-rpc-client
        node --input-type=module -e 'var f;import{create as e,globSource as l}from"kubo-rpc-client";let client=e({url:process.env.IPFS_URL,headers:{"CF-Access-Client-Id":process.env.CF_ID,"CF-Access-Client-Secret":process.env.CF_SECRET}});for await(f of client.addAll(l(process.env.IPFS_FOLDER,"**/*")))console.log(f);let n=await client.name.publish(f.cid);console.log(n);'
