# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [ ubuntu-18.04 ]

    steps:
      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    
    - name: Install global NPM packages
      run: npm install --global yarn ipfs-deploy
      
    - name: Build website 
      run: |
        cd $GITHUB_WORKSPACE
        yarn
        yarn prod
      
    - name: Upload to infuria 
      run: |
        ipfs-deploy -p infura build/
